version: 2
updates:
  - package-ecosystem: "npm"  # Actualización para proyectos Node.js (npm)
    directory: "/"  # Ubicación del archivo package.json
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "pip"  # Actualización para proyectos Python (pip)
    directory: "/"  # Ubicación del archivo requirements.txt
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "maven"  # Actualización para proyectos Java (Maven)
    directory: "/"  # Ubicación del archivo pom.xml
    schedule:
      interval: "monthly"  # Actualizaciones mensuales

  - package-ecosystem: "gradle"  # Actualización para proyectos Java (Gradle)
    directory: "/"  # Ubicación del archivo build.gradle
    schedule:
      interval: "monthly"  # Actualizaciones mensuales

  - package-ecosystem: "rubygems"  # Actualización para proyectos Ruby (Gemfile)
    directory: "/"  # Ubicación del archivo Gemfile
    schedule:
      interval: "daily"  # Actualizaciones diarias

  - package-ecosystem: "nuget"  # Actualización para proyectos .NET (NuGet)
    directory: "/"  # Ubicación del archivo packages.config
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "composer"  # Actualización para proyectos PHP (Composer)
    directory: "/"  # Ubicación del archivo composer.json
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "terraform"  # Actualización para proyectos Terraform
    directory: "/"  # Ubicación del archivo terraform.tf
    schedule:
      interval: "monthly"  # Actualizaciones mensuales

  - package-ecosystem: "cargo"  # Actualización para proyectos Rust (Cargo)
    directory: "/"  # Ubicación del archivo Cargo.toml
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "elixir"  # Actualización para proyectos Elixir
    directory: "/"  # Ubicación del archivo mix.exs
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "go_modules"  # Actualización para proyectos Go (Go Modules)
    directory: "/"  # Ubicación del archivo go.mod
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "haskell"  # Actualización para proyectos Haskell
    directory: "/"  # Ubicación del archivo cabal.config
    schedule:
      interval: "monthly"  # Actualizaciones mensuales

  - package-ecosystem: "hex"  # Actualización para proyectos Elixir (Hex)
    directory: "/"  # Ubicación del archivo mix.exs
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "jekyll"  # Actualización para proyectos Jekyll
    directory: "/"  # Ubicación del archivo _config.yml
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "docker"  # Actualización para imágenes Docker
    directory: "/"  # Ubicación del archivo Dockerfile
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "vcpkg"  # Actualización para proyectos C++ (vcpkg)
    directory: "/"  # Ubicación del archivo vcpkg.json
    schedule:
      interval: "monthly"  # Actualizaciones mensuales

  - package-ecosystem: "bundler"  # Actualización para proyectos Ruby (Bundler)
    directory: "/"  # Ubicación del archivo Gemfile.lock
    schedule:
      interval: "daily"  # Actualizaciones diarias

  - package-ecosystem: "packagist"  # Actualización para proyectos PHP (Packagist)
    directory: "/"  # Ubicación del archivo composer.json
    schedule:
      interval: "weekly"  # Actualizaciones semanales

