version: 2
updates:
  # Actualizaciones para proyectos Node.js (npm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    automerge: true
    # Ignorar versiones específicas si es necesario
    ignore:
      - dependency-name: "legacy-package"
        versions: ["<1.0.0"]

  # Actualizaciones para proyectos Python (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Actualizaciones para proyectos Java (Maven)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"

  # Actualizaciones para proyectos Java (Gradle)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"

  # Actualizaciones para proyectos Ruby (Bundler)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly" # Reducido de diario a semanal
    automerge: false

  # Actualizaciones para proyectos PHP (Composer)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

  # Actualizaciones para proyectos Terraform
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "monthly"

  # Actualizaciones para proyectos Rust (Cargo)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # Actualizaciones para proyectos Go (Go Modules)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Actualizaciones para imágenes Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    automerge: true
    # Priorizar actualizaciones de seguridad
    commit-message:
      prefix: "[SECURITY]"

  # Actualizaciones para acciones de GitHub
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # Reducido de diario a semanal
    automerge: true

# Notas adicionales:
# - Automerge está habilitado para npm, Docker y GitHub Actions para actualizaciones menores o de seguridad.
# - Se limita el número de PRs abiertos simultáneamente para npm y pip para evitar sobrecarga.
# - La frecuencia de actualización se ajusta según el ecosistema para equilibrar la necesidad de actualizaciones y evitar ruido excesivo.



