version: 2
updates:
  - package-ecosystem: "npm"  # Actualización para proyectos Node.js (npm)
    directory: "/"  # Ubicación del archivo package.json
    schedule:
      interval: "weekly"  # Actualizaciones semanales
    ignore:
      - dependency-name: "nth-check"
        versions:
          - "1.0.2"
        reason: "No existe versión parcheada; se espera actualización en upstream"

  - package-ecosystem: "pip"  # Actualización para proyectos Python (pip)
    directory: "/"  # Ubicación del archivo requirements.txt
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "maven"  # Actualización para proyectos Java (Maven)
    directory: "/"  # Ubicación del archivo pom.xml
    schedule:
      interval: "monthly"  # Actualizaciones mensuales

  - package-ecosystem: "gradle"  # Actualización para proyectos Java (Gradle)
    directory: "/"  # Ubicación del archivo build.gradle
    schedule:
      interval: "monthly"  # Actualizaciones mensuales

  - package-ecosystem: "bundler"  # Actualización para proyectos Ruby (Gemfile)
    directory: "/"  # Ubicación del archivo Gemfile
    schedule:
      interval: "daily"  # Actualizaciones diarias

  - package-ecosystem: "composer"  # Actualización para proyectos PHP (composer)
    directory: "/"  # Ubicación del archivo composer.json
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "terraform"  # Actualización para proyectos Terraform
    directory: "/"  # Ubicación del archivo terraform.tf
    schedule:
      interval: "monthly"  # Actualizaciones mensuales

  - package-ecosystem: "cargo"  # Actualización para proyectos Rust (Cargo)
    directory: "/"  # Ubicación del archivo Cargo.toml
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "gomod"  # Actualización para proyectos Go (Go Modules)
    directory: "/"  # Ubicación del archivo go.mod
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "docker"  # Actualización para imágenes Docker
    directory: "/"  # Ubicación del archivo Dockerfile
    schedule:
      interval: "weekly"  # Actualizaciones semanales

  - package-ecosystem: "github-actions"  # Actualización para acciones de GitHub
    directory: "/"  # Ubicación del archivo .github/workflows/
    schedule:
      interval: "daily"  # Actualizaciones diarias
