# Configuración de GitHub Pages
# Este archivo define la configuración específica para el despliegue en GitHub Pages

# Configuración de la fuente de publicación
source:
  branch: gh-pages
  path: /

# Configuración de Jekyll (deshabilitado para sitios estáticos)
jekyll: false

# Configuración de seguridad
security:
  # Permitir contenido mixto (HTTP/HTTPS)
  mixed_content: false
  
  # Configuración de CSP (Content Security Policy)
  content_security_policy: |
    default-src 'self';
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://unpkg.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net;
    font-src 'self' https://fonts.gstatic.com;
    img-src 'self' data: https:;
    media-src 'self' https:;
    connect-src 'self' https:;
    frame-src 'self' https:;

# Configuración de redirecciones
redirects:
  # Redireccionar rutas comunes
  /home: /
  /index: /
  /main: /

# Configuración de caché
cache:
  # Archivos estáticos (1 año)
  static: 31536000
  # Archivos HTML (1 hora)
  html: 3600
  # Archivos CSS/JS (1 semana)
  assets: 604800
