name: Generate Sitemap

on:
  push:
    branches: [main] # o "master", según tu rama
  workflow_dispatch:

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1.10.2
        with:
          base-url-path: https://1inmortal.github.io/githubpagetest/

      - name: Commit sitemap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Add/update sitemap.xml"
          git push
