services:
  python-proyecto-x:
    build:
      context: ./Evidencias/Proyecto x
    container_name: python-proyecto-x
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists in ./Evidencias/Proyecto x
    # No ports exposed; adjust if Nmap.py listens on a port

  python-llama-cpp-python:
    build:
      context: ./laboratorio/llama-cpp-python
    container_name: python-llama-cpp-python
    restart: unless-stopped
    # No ports exposed; adjust if run_llama.py listens on a port

  python-seguridad-python:
    build:
      context: ./presentacion/seguridad/seguridad-python
    container_name: python-seguridad-python
    restart: unless-stopped
    # env_file: ./.env  # Uncomment if .env file exists in ./presentacion/seguridad/seguridad-python
    # No ports exposed; adjust if app.py listens on a port

  javascript-react-ui-login:
    build:
      context: ./react-ui-login
    container_name: javascript-react-ui-login
    restart: unless-stopped
    init: true
    ports:
      - "3000:3000"  # React app served on port 3000
    # No env_file by default; add if needed

  java-login:
    build:
      context: ./diseños/login
    container_name: java-login
    restart: unless-stopped
    # No ports exposed; adjust if Main.java listens on a port

# No external services (databases, caches, etc.) detected in documentation or code
# No volumes section included as no persistent data services are present
