version: '3.8'

services:
  # Base de datos SQLite (usando volumen para persistencia)
  database:
    image: alpine:latest
    container_name: githubpagetest-db
    restart: unless-stopped
    volumes:
      - ./server/prisma:/app/prisma
      - db_data:/app/data
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache sqlite &&
        mkdir -p /app/data &&
        sqlite3 /app/data/dev.db 'CREATE TABLE IF NOT EXISTS _prisma_migrations (id VARCHAR(36) PRIMARY KEY, checksum VARCHAR(64) NOT NULL, finished_at DATETIME(3), migration_name VARCHAR(255) NOT NULL, logs TEXT, rolled_back_at DATETIME(3), started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, applied_steps_count INTEGER UNSIGNED NOT NULL DEFAULT 0);' &&
        tail -f /dev/null
      "

  # API Backend
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: githubpagetest-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./server:/app
      - /app/node_modules
      - db_data:/app/data
    depends_on:
      - database
    command: npm run dev

  # Frontend (servidor estático)
  frontend:
    image: nginx:alpine
    container_name: githubpagetest-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  db_data:
    driver: local
