name: Secret Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for secrets with trufflehog
        uses: trufflesecurity/trufflehog@main
        with:
          scanArguments: --regex --entropy=False . 