name: Generate Sitemap

on:
  push:
    branches: [main]
    paths:
      - '**/*.html'
      - '**/*.md'
  workflow_dispatch:

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1.10.2
        with:
          base-url-path: https://1inmortal.github.io/githubpagetest/
          additional-paths: |
            /index.html
            /Blog/
            /Certificados/
            /Evidencias/
            /assets/
            /data/
            /docs/
            /tools/
            /src/
            /react-ui-login/
            /README.md
            /CONTRIBUTING.md
            /SECURITY.md
            /CODE_OF_CONDUCT.md
            /LICENSE

      - name: Commit and push sitemap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git diff --staged --quiet || git commit -m "Update sitemap.xml [skip ci]"
          git push 