---
# GitHub Actions workflow for static website deployment
# More GitHub Actions for static sites:
#   https://github.com/actions

name: Build and deploy static website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Check if package.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'package.json'

      - name: Install dependencies if package.json exists
        if: steps.check_files.outputs.files_exists == true
        run: npm ci

      - name: Build project if package.json exists
        if: steps.check_files.outputs.files_exists == true
        run: npm run build

      - name: Prepare files for deployment
        run: |
          # Crear directorio temporal para archivos del sitio
          mkdir -p site-files
          
          # Copiar solo archivos necesarios para el sitio web
          cp -r index.html site-files/ || true
          cp -r *.html site-files/ || true
          cp -r assets/ site-files/ || true
          cp -r Blog/ site-files/ || true
          cp -r Certificados/ site-files/ || true
          cp -r data/ site-files/ || true
          cp -r docs/ site-files/ || true
          cp -r tools/ site-files/ || true
          cp -r src/ site-files/ || true
          cp -r react-ui-login/ site-files/ || true
          cp -r *.md site-files/ || true
          cp -r *.json site-files/ || true
          cp -r *.xml site-files/ || true
          cp -r *.txt site-files/ || true
          cp -r sw.js site-files/ || true
          cp -r manifest.json site-files/ || true
          
          # Excluir archivos grandes
          find site-files -name "*.mp3" -delete
          find site-files -name "*.mp4" -delete
          find site-files -name "*.zip" -delete
          find site-files -name "*.avi" -delete
          find site-files -name "*.mov" -delete
          find site-files -name "*.wav" -delete
          find site-files -name "*.flac" -delete
          find site-files -name "*.mkv" -delete
          
          # Excluir directorios grandes
          rm -rf site-files/Evidencias/Audio || true
          rm -rf site-files/Evidencias/Proyecto\ x/src/Audio || true
          rm -rf site-files/Evidencias/laboratorio/mp4 || true
          rm -rf site-files/Evidencias/presentacion/src/Audio || true
          rm -rf site-files/MP4 || true
          rm -rf site-files/MP4.zip || true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: website-app
          path: site-files

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: write  # This is required for pushing to gh-pages

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: website-app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          